{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rstac
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rstac_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rstac/rstac_{{ version }}.tar.gz
  sha256: 0623864b7efb6ffd684834839b8196f32d9b8017add3935d21edf544efd88a08

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-crayon
    - r-httr
    - r-jpeg
    - r-jsonlite
    - r-lifecycle
    - r-magrittr
    - r-png
    - r-sf
  run:
    - r-base
    - r-crayon
    - r-httr
    - r-jpeg
    - r-jsonlite
    - r-lifecycle
    - r-magrittr
    - r-png
    - r-sf

test:
  commands:
    - $R -e "library('rstac')"           # [not win]
    - "\"%R%\" -e \"library('rstac')\""  # [win]

about:
  home: https://brazil-data-cube.github.io/rstac/
  dev_url: https://github.com/brazil-data-cube/rstac
  license: MIT
  summary: Provides functions to access, search and download spacetime earth observation data via SpatioTemporal Asset Catalog (STAC). This package supports the version 0.8.1 or higher of the STAC specification (<http://stacspec.org>).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger
    - rolfsimoes
    - OldLipe
    - gqueiroz
