{% set version = "0.9.1-5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rstac
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rstac_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rstac/rstac_{{ version }}.tar.gz
  sha256: 6c6d0341c3fd13d61301ad0441ec87356ed2d695a3de9c650edca8c513f99622

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-crayon
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-magrittr
  run:
    - r-base
    - r-crayon
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-magrittr

test:
  commands:
    - $R -e "library('rstac')"           # [not win]
    - "\"%R%\" -e \"library('rstac')\""  # [win]

about:
  home: https://github.com/brazil-data-cube/rstac
  license: MIT
  summary: Provides functions to access, search and download spacetime earth observation data via SpatioTemporal Asset Catalog (STAC). This package supports the version 0.8.1 or higher of the STAC specification (<http://stacspec.org>).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger
    - rolfsimoes
    - OldLipe
    - gqueiroz

# Package: rstac
# Title: Client Library for SpatioTemporal Asset Catalog
# Version: 0.9.1-5
# Authors@R: c(person("Brazil Data Cube Team", email = "brazildatacube@inpe.br", role = c("cre", "aut")), person(given = "National Institute for Space Research (INPE)", role = c("cph")))
# Description: Provides functions to access, search and download spacetime earth observation data via SpatioTemporal Asset Catalog (STAC). This package supports the version 1.0.0 of the STAC specification (<https://github.com/radiantearth/stac-spec>). For further details see Simoes et al. (2021) <doi:10.1109/IGARSS47720.2021.9553518>.
# License: MIT + file LICENSE
# URL: https://github.com/brazil-data-cube/rstac
# BugReports: https://github.com/brazil-data-cube/rstac/issues
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# Depends: R (>= 3.5)
# Imports: httr, crayon, utils, magrittr, jsonlite, lifecycle
# Suggests: covr, testthat, vcr
# NeedsCompilation: no
# Packaged: 2021-10-31 00:09:28 UTC; sits
# Author: Brazil Data Cube Team [cre, aut], National Institute for Space Research (INPE) [cph]
# Maintainer: Brazil Data Cube Team <brazildatacube@inpe.br>
# Repository: CRAN
# Date/Publication: 2021-10-31 21:10:02 UTC
